//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PickAny_.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineItem
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<double> Rate { get; set; }
        public int Quantity { get; set; }
        public Nullable<double> Tax { get; set; }
        public double Total { get; set; }
    }
}
